site_name: Documentation
site_author: Christian Diener
site_url: https://cdiener.github.io/architeuthis

repo_url: https://github.com/cdiener/architeuthis
repo_name: cdiener/architeuthis

nav:
  - Home: index.md
  - Installation: install.md
  - User Guide:
    - Lineage annotation: lineage.md
    - Merging: merge.md
    - Mapping Analysis: mapping.md
    - Filtering: filter.md
  - Releases: release_notes.md

theme:
  name: material
  locale: en
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  logo: architeuthis.webp
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

# Formatting options
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes

plugins:
  - search:
      lang: en