# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Install optional dependencies
      run: |
        go get -v github.com/shenwei356/taxonkit/taxonkit
        go install -v github.com/shenwei356/taxonkit/taxonkit
        wget ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
        tar -xf taxdump.tar.gz
        mkdir $HOME/.taxonkit && cp *.dmp $HOME/.taxonkit/
        ls -alh `go env GOPATH`/bin

    - name: Test
      run: PATH=$PATH:`go env GOPATH`/bin go test -v ./...
